apiVersion: v1
kind: Namespace
metadata:
  name: user-management
  labels:
    name: user-management
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-management-sa
  namespace: user-management
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: user-management
  name: user-management-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-management-rolebinding
  namespace: user-management
subjects:
- kind: ServiceAccount
  name: user-management-sa
  namespace: user-management
roleRef:
  kind: Role
  name: user-management-role
  apiGroup: rbac.authorization.k8s.io
